version: '3.2'

services:
  jupyter:
    image: jupyter
    build: .
    container_name: jupyter
    working_dir: /home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./data:/home/jovyan/data
      - ./config:/home/jovyan/config
    command: start-notebook.sh --NotebookApp.token=''
